services:
  api_kenzie_courses:
    container_name: kenzieCoursesApi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - pg_kenzie_courses
    command: bash -c "yarn migration:run && yarn dev"
  pg_kenzie_courses:
    container_name: containerPostgres
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5434:5432
